apiVersion: split.smi.spec.io/v1alpha3
kind: TrafficSplit
metadata:
  name: backend-ts
spec: 
  service: backend-svc
  backends:
  - service: backend-v1
    weight: 75
  - service: backend-v2
    weight: 25